[package]
name = "voicevox_runtime"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false # not yet

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.18.0"
ort = "1.15.4"
thiserror = "1.0.48"
